services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud_mysql
      MYSQL_USER: user_crud_api
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"


      